#!/bin/bash
# auto-handoff.sh — On Stop, writes a clean structured session handoff to memory/session_handoff.md
# NO Claude subprocess, NO Python, NO network. Pure bash + jq reading local JSONL.
# Output is designed for semantic merge on next SessionStart (see session-context-loader.sh).

source "${HOME}/.claude/hooks/hooks-common.sh"
rate_limit_check "auto-handoff" 60

JQ=$(command -v jq 2>/dev/null || echo "${HOME}/.claude/bin/jq.exe")

# Read Stop hook input (has stop_reason)
INPUT=$(cat 2>/dev/null)
STOP_REASON=$(echo "$INPUT" | "$JQ" -r '.stop_reason // "end_turn"' 2>/dev/null || echo "end_turn")
[ "$STOP_REASON" = "tool_use" ] && exit 0

# Locate project memory dir matching current working directory
PROJECT_NAME=$(echo "$PWD" | tr '/' '-' | sed 's/^-//' | sed 's/-/--/')
MEMORY_DIR="${HOME}/.claude/projects/${PROJECT_NAME}/memory"
[ ! -d "$MEMORY_DIR" ] && exit 0

# Find most recent session JSONL for this project
SESSION_DIR="${HOME}/.claude/projects/${PROJECT_NAME}"
LATEST=$(ls -t "$SESSION_DIR"/*.jsonl 2>/dev/null | head -1)
[ -z "$LATEST" ] && exit 0

# Require at least 3 tool calls — short sessions don't need handoff
TOOL_CALLS=$(grep -c '"toolUseResult"' "$LATEST" 2>/dev/null || echo 0)
[ "${TOOL_CALLS:-0}" -lt 3 ] && exit 0

DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H:%M")

# Sentence-boundary truncation — cuts at last '.', '!', '?', or ':' before max chars.
# Falls back to word boundary if no sentence end found. Appends "…" if truncated.
smart_truncate() {
  local text="$1"
  local max="${2:-300}"
  local len=${#text}
  [ "$len" -le "$max" ] && { echo "$text"; return; }
  local cut="${text:0:$max}"
  # Try sentence boundary (last . ! ? or :)
  local sent="${cut%[.!?:]*}[.!?:]*"
  local sent_end
  sent_end=$(echo "$cut" | grep -oE '.*[.!?:]' | tail -1)
  if [ -n "$sent_end" ] && [ ${#sent_end} -ge $((max / 2)) ]; then
    echo "${sent_end}…"
    return
  fi
  # Fallback to last word boundary
  echo "${cut% *}…"
}

# Extract last 5 user prompts (non-system)
USER_PROMPTS=$("$JQ" -r '
  select(.message.role == "user") |
  .message.content |
  if type == "string" then .
  else (.[] | select(.type == "text") | .text)
  end
' "$LATEST" 2>/dev/null | grep -v '^<' | grep -v '^$' | grep -v 'system-reminder' | tail -5)

# Files touched (unique, last 10)
FILES=$(grep -o '"file_path":"[^"]*"' "$LATEST" 2>/dev/null | cut -d'"' -f4 | sort -u | tail -10)

# Last single assistant message (not last 20 concatenated — that was the garbling bug)
LAST_SAY=$("$JQ" -r '
  select(.message.role == "assistant") |
  .message.content |
  if type == "array" then (.[] | select(.type == "text") | .text)
  else .
  end
' "$LATEST" 2>/dev/null | grep -v '^$' | tail -30 | tr '\n' ' ' | sed 's/  */ /g')

HANDOFF="$MEMORY_DIR/session_handoff.md"

{
  printf -- '---\n'
  printf 'name: session_handoff\n'
  printf 'description: Auto-generated handoff from last session — review for merge into memory\n'
  printf 'type: project\n'
  printf 'generated: %sT%s\n' "$DATE" "$TIME"
  printf 'merge_status: pending\n'
  printf -- '---\n\n'

  printf '**Last session**: %s %s (%s tool calls)\n\n' "$DATE" "$TIME" "$TOOL_CALLS"

  printf '## Recent user requests\n\n'
  if [ -n "$USER_PROMPTS" ]; then
    echo "$USER_PROMPTS" | while IFS= read -r line; do
      [ -n "$line" ] && printf -- '- %s\n' "$(smart_truncate "$line" 200)"
    done
  else
    printf -- '- (none extracted)\n'
  fi
  printf '\n'

  printf '## Files touched\n\n'
  if [ -n "$FILES" ]; then
    echo "$FILES" | while IFS= read -r f; do
      [ -n "$f" ] && printf -- '- `%s`\n' "$f"
    done
  else
    printf -- '- (none)\n'
  fi
  printf '\n'

  if [ -n "$LAST_SAY" ]; then
    printf '## Last assistant note\n\n%s\n\n' "$(smart_truncate "$LAST_SAY" 500)"
  fi

  printf -- '---\n'
  printf '*Auto-generated by auto-handoff.sh. On next session start, Claude will be prompted to semantically merge significant data into memory/*.md — overwriting or updating existing entries rather than duplicating.*\n'
} > "$HANDOFF"

exit 0
